name: MCTrapsHelpOp
version: 1.0.0
author: KajmaczeK
main: pl.kajmaczek.mctraps.helpop.HelpOP
website: https://mctraps.eu
commands:
  helpop:
    description: "Komenda /helpop"
permissions:
  tools.helpop.banned:
    description: "Blokada na helpopa"
    default: false
  tools.helpop.read:
    description: "Pozwala na odczytywanie helpopa"
    default: op